const KEY="rafaqatedits_gemini_key";
const MODEL="gemini-3.8-flash";
const $=id=>document.getElementById(id);
function openSettings(){const s=$("settings");if(s){s.classList.add("show");const k=$("apiKey");if(k)k.value=localStorage.getItem(KEY)||""}}
function closeSettings(){const s=$("settings");if(s)s.classList.remove("show")}
function setStatus(connected){const s=$("status");if(!s)return;s.textContent=connected?"Connected":"Not connected";s.style.color=connected?"#67e8b1":"#d49b50"}
function saveKey(){const k=$("apiKey")?.value.trim();if(!k){alert("Please paste your Gemini API key.");return}localStorage.setItem(KEY,k);closeSettings();setStatus(true);if($("messages"))add("ai","Gemini API connected. Ask me anything!")}
function clearKey(){localStorage.removeItem(KEY);if($("apiKey"))$("apiKey").value="";setStatus(false);closeSettings()}
function add(type,text){const box=$("messages");if(!box)return null;const m=document.createElement("div");m.className="msg "+type;m.textContent=text;box.appendChild(m);box.scrollTop=box.scrollHeight;return m}
async function sendMessage(){const input=$("prompt");if(!input)return;const text=input.value.trim();if(!text)return;const key=localStorage.getItem(KEY);if(!key){openSettings();alert("First connect your Gemini API key.");return}add("user",text);input.value="";const wait=add("ai","Thinking…");try{const url=`https://generativelanguage.googleapis.com/v1beta/models/${MODEL}:generateContent?key=${encodeURIComponent(key)}`;const res=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({contents:[{role:"user",parts:[{text:text}]}]})});const data=await res.json();if(!res.ok)throw new Error(data?.error?.message||"Gemini API request failed.");const answer=data?.candidates?.[0]?.content?.parts?.map(p=>p.text||"").join("")||"No text response received.";wait.textContent=answer}catch(e){wait.textContent="API Error: "+e.message+"\n\nCheck your Gemini API key and API access."}}
window.addEventListener("load",()=>setStatus(!!localStorage.getItem(KEY)));